name: Format PHP

on: push

# on:
#   push:
#     branches:
#       - master

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Run php-cs-fixer
      uses: docker://oskarstark/php-cs-fixer-ga

    - uses: yelizariev/git-auto-commit-action@custom-author-and-token
      with:
        commit_message: Apply php-cs-fixer changes
        commit_author_name: Marc Demo (Github Actions)
        commit_author_email: i18n-bot@it-projects.info
        commit_options: '--no-verify'
        branch: master
        repository: .
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
