name: Format PHP

on: push

# on:
#   push:
#     branches:
#       - master

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Run php-cs-fixer
      uses: docker://oskarstark/php-cs-fixer-ga

    - uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        commit_message: Apply php-cs-fixer changes
        commit_options: '--no-verify'
        # branch: master
        repository: .
        branch: ${{ github.head_ref }}
